### ISSUE TITLE
New entries

### ISSUE THREAD

**Issue by antranapp** [antranapp/awesome-tca#4]
https://github.com/alexjohnj/Sauna
https://github.com/renaudjenny/MemoArt

**Comment by antranapp** [comment]
https://github.com/darrarski/WallpapersStudio-iOS

**Comment by antranapp** [comment]
https://github.com/kaishin/markoff

**Comment by stephencelis** [comment]
https://github.com/pointfreeco/isowords ;)
https://github.com/RogyMD/TCAminesweeper

**Comment by antranapp** [comment]
Added your projects, thank you for awesome open-source code: @stephencelis @alexjohnj @darrarski @kaishin @renaudjenny @RogyMD
